### ISSUE TITLE
[Request/Idea] 60 FPS in Inkopolis Plaza/Splatsville

### ISSUE THREAD

**Issue by ManiaSonicRUS** [Coxxs/public-pchtxt#4]
I hope its possible, it would make the lobbies feel much smoother. I really like spending time in lobbies but its such a shame them being locked at 30 FPS

**Comment by Coxxs** [comment]
Thanks for the suggestion!

There is indeed a patch to enable *Plaza* 60fps, but since it's not made by me and private, I'm not sure if I have the right to re-release it.
If you find a publicly available 60fps patch, let me know and I'll port it to latest version!

P.S. [Flexlion](https://gamebanana.com/wips/70362) supports 60fps in Plaza. Also, because of Dynamic Resolution, the resolution will be automatically reduced without overclocking the GPU.

**Comment by Coxxs** [comment]
Found the source of that patch: https://github.com/theboy181/switch-ptchtxt-mods/tree/main/Splatoon%203/%5B0100C2500FC20000%5D/1.1.1

**Comment by ManiaSonicRUS** [comment]
Thank you! But I don't think it works =(, its still 30 fps and I'm on yuzu EA 4065

**Comment by ManiaSonicRUS** [comment]
For some reason it stops working after I open inventory. Is there any fix? Re-entering the cities helps, but it's still noticeable.
